services:
  # PostgreSQL 数据库服务
  mysql:
    image: mysql:5.7
    container_name: dev-mysql
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - middleware

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_ERLANG_COOKIE: my-secret-cookie
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - "5672:5672"   # AMQP 端口
      - "15672:15672" # 管理界面端口
    labels:
      NAME: "rabbitmq"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - middleware
      
  redis:
    image: redis:6.0
    container_name: dev-redis
    platform: linux/x86_64
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - ./redis:/data
      - redis-data:/data
    networks:
      - middleware

volumes:
  mysql-data:
  redis-data:
  rabbitmq-data:

networks:
  middleware:
    driver: bridge